steps:
# step 0 store buil info
- id: "Store Values"
  name: ubuntu
  entrypoint: bash
  args:
    - -c
    - |
      # save the commit sha & build date
      NOW=$(date +"%Y-%m-%d %T")
      echo $BRANCH_NAME $SHORT_SHA $NOW > BUILDINFO
# step 1 build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 'gcr.io/$PROJECT_ID/psi:$SHORT_SHA', 
    '-t', 'gcr.io/$PROJECT_ID/psi:latest', 
    '--build-arg','COMMITSHA=$COMMIT_SHA',
    '--build-arg','SHORTSHA=$SHORT_SHA',
    '--cache-from', 'gcr.io/$PROJECT_ID/psi:latest',
    '.']
# step 2 push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/psi:$SHORT_SHA"]
# step 3 deploy container image to GKE
- name: "gcr.io/cloud-builders/kubectl"
  args: ['set', 'image', 'deployment/psi', 'psi=gcr.io/$PROJECT_ID/psi:$SHORT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER'
images:
- gcr.io/$PROJECT_ID/psi:$SHORT_SHA
- gcr.io/$PROJECT_ID/psi:latest