steps:
# step0 build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 'gcr.io/$PROJECT_ID/psi:$SHORT_SHA', 
    '-t', 'gcr.io/$PROJECT_ID/psi:latest', 
    '--build-arg','COMMITSHA=$COMMIT_SHA',
    '--build-arg','SHORTSHA=$SHORT_SHA',
    '--cache-from', 'gcr.io/$PROJECT_ID/psi:latest',
    '.']
# step1 push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/psi:$SHORT_SHA"]
# step 2 deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment.yaml
  - --image=gcr.io/$PROJECT_ID/psi:$SHORT_SHA
  - --location=${_CLOUDSDK_COMPUTE_ZONE}
  - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
images:
- gcr.io/$PROJECT_ID/psi:$SHORT_SHA
- gcr.io/$PROJECT_ID/psi:latest